print('DEBUG MODE')
print('1 ATTEMPT(S) LEFT\n')
print('PROVIDE')
print('SETTING')
print('CANTINA')
print('CUTTING')
print('HUNTERS')
print('SURVIVE')
print('HEARING')
print('HUNTING')
print('REALIZE')
print('NOTHING')
print('OVERLAP')
print('FINDING')
print('PUTTING\n')
input('Enter password >')
print('LOGIN FAILURE - TERMINAL LOCKED\n')
print('PLEASE CONTACT AN ADMINISTRATOR\n')
input('PRESS ENTER TO EXIT')